spring:
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
server:
  port: 8888